package com.lb.generator.entity;

import com.lb.generator.annotation.LbCommand;
import com.lb.generator.annotation.LbProperty;

import lombok.Data;
import lombok.extern.slf4j.Slf4j;

/**
 * This code is generated by FreeMarker
 *
 */

@Data
@Slf4j
public class ${service.serviceType}Model
{

    /********** attribute ***********/
<#list service.properties as property>
    @LbProperty(writeable =  ${property.writeable})
    private ${property.javaType} ${property.propertyName};

</#list>

}